// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAmV-u88TJJ73ApOzS83KU9TclFefudc0',
    appId: '1:802968136615:web:ad4f5bae0ef0a92f67a482',
    messagingSenderId: '802968136615',
    projectId: 'yutytu-77f99',
    authDomain: 'yutytu-77f99.firebaseapp.com',
    storageBucket: 'yutytu-77f99.appspot.com',
    measurementId: 'G-8QNTPH8ETK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiCALBJl3s6VRd6ANyubLGoAPPUMJ5Nhg',
    appId: '1:802968136615:android:92ee0350d357fbb467a482',
    messagingSenderId: '802968136615',
    projectId: 'yutytu-77f99',
    storageBucket: 'yutytu-77f99.appspot.com',
  );
}
